apiVersion: v1
kind: Service
metadata:
  name: gitserver
  labels:
    name: gitserver
spec:
  ports:
    - port: 22
      name: ssh
      targetPort: 22
    - port: 2222
      name: ftps
      targetPort: 2222
  selector:
    name: gitserver
    tier: backend