apiVersion: v1
kind: Service
metadata:
  name: vaadin-example-web
  labels:
    name: vaadin-example-web
spec:
  ports:
    - port: 8080
      name: http-port
  selector:
    name: vaadin-example-web
    tier: frontend
  type: LoadBalancer