apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
  labels:
    name: eurekaserver
spec:
  ports:
    - port: 8761
      name: http-port
  selector:
    name: eurekaserver
    tier: backend
  type: LoadBalancer