version: '3'
services:
  jdkserver:
      container_name: jdkserver
      build: jdkserver
      image: jdkserver:latest

  gitserver:
    container_name: gitserver
    build: ./gitserver
    image: gitserver:latest
    expose:
      - 22:22
      - 2222:22
    ports:
      - "22:22"
      - "2222:22"
    networks:
      backend:
        aliases:
          - gitserver

  elasticsearch:
    container_name: elasticsearch
    build: ./elasticsearch
    image: elasticsearch:latest
    environment:
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    expose:
      - 9200
      - 9300
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      backend:
        aliases:
          - elasticsearch
    depends_on:
      -  jdkserver

  mysql:
    container_name: mysql
    build: ./mysql
    image: mysql:latest
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      backend:
        aliases:
          - mysql

  configserver:
    container_name: configserver
    build: ./configserver
    image: configserver:latest
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: git@gitserver:/srv/project.git
    expose:
      - 8888
    ports:
      - "8888:8888"
    networks:
      backend:
        aliases:
          - configserver
    depends_on:
      -  jdkserver

  eurekaserver:
    container_name: eurekaserver
    build: ./eurekaserver
    image: eurekaserver:latest
    expose:
      - 8761
    ports:
      - "8761:8761"
    networks:
      eureka:
        aliases:
          - eurekaserver
    depends_on:
      -  jdkserver

  serviceserver:
    container_name: serviceserver
    build: ./serviceserver
    image: serviceserver:latest
    environment:
          SPRING_CLOUD_CONFIG_URI: http://configserver:8888
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka
    expose:
      - 8881
    ports:
      - "8881:8881"
    networks:
      backend:
        aliases:
          - serviceserver
      eureka:
        aliases:
          - serviceserver
    depends_on:
      -  jdkserver

  webapp:
    container_name: webapp
    build:
      context: ./webapp
    image: vaadin-example-web:latest
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      eureka:
        aliases:
          - webapp
    depends_on:
      -  jdkserver

  apiapp:
      container_name: apiapp
      build: ./apiapp
      image: vaadin-example-api:latest
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka
      expose:
        - 8181
      ports:
        - "8181:8181"
      networks:
        eureka:
          aliases:
            - apiapp
      depends_on:
        -  jdkserver

networks:
    eureka:
    backend: