apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
spec:
  ports:
    - port: 9200
      name: http-port
    - port: 9300
      name: tcp-port
  selector:
    name: elasticsearch
    tier: backend
  type: LoadBalancer